export class ExamQuiz {
    examQuizId :Int32Array;
    examQuestion: string;
    examIsCorrect: string;
    examQuizName:string;
    examOption1 : string;
    examOption2: string;
    examOption3 : string;
    examOption4 : string;
    examOption5 : string;
    examQuestionImageURL:string;
    examOptionImageURL1:string;
    examOptionImageURL2:string;
    examOptionImageURL3:string;
    examOptionImageURL4:string;
    examOptionImageURL5:string;
    examQuestionImage:string;
    examOptionImage1 :string;
    examOptionImage2 :string;
    examOptionImage3 :string;
    examOptionImage4 :string;
    examOptionImage5 :string;
    examTagTopic :string;
    examQuizCode :string;
    examThumbnailImage:string;
    courseId:string;
    examTime: number;
    quizId :string;
    isBlocked:boolean;
}